version: 2
jobs:
  build:
    docker:
      - image: 705180747189.dkr.ecr.ap-northeast-1.amazonaws.com/c-compiler-go:2.0
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

    working_directory: /go/wkdir
    steps:
      - checkout
      - run:
          name: lint
          command: |
            golangci-lint run ./...
      - run: go test -v ./...
